create table users
(
    id       bigint generated by default as identity,
    email    varchar(255) not null,
    password varchar(255) not null,
    bio      varchar(255),
    image    varchar(255),
    name     varchar(255) not null,
    primary key (id)
)